[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1920x1080x24 -ac
autorestart=true
priority=10

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -nopw -forever -shared -rfbport 5900
autorestart=true
priority=20

[program:websockify]
command=/usr/bin/websockify --web /usr/share/novnc 6080 localhost:5900
autorestart=true
priority=30

[program:chromium]
command=/usr/bin/chromium-browser --no-sandbox --disable-gpu --disable-software-rasterizer --start-maximized --remote-debugging-port=9222
environment=DISPLAY=":99"
autorestart=true
priority=40
