/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAssistButton: typeof import('@/components/vort-biz/ai-assist-button')['AiAssistButton']
    DeleteRecord: typeof import('@/components/vort-biz/delete-record')['DeleteRecord']
    MarkdownView: typeof import('@/components/vort-biz/editor')['MarkdownView']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableActions: typeof import('@/components/vort-biz/table-actions')['TableActions']
    TableActionsItem: typeof import('@/components/vort-biz/table-actions')['TableActionsItem']
    VortAlert: typeof import('@/components/vort/alert')['Alert']
    VortAutoComplete: typeof import('@/components/vort/auto-complete')['AutoComplete']
    VortButton: typeof import('@/components/vort/button')['Button']
    VortCard: typeof import('@/components/vort/card')['Card']
    VortCheckbox: typeof import('@/components/vort/checkbox')['Checkbox']
    VortDatePicker: typeof import('@/components/vort/date-picker')['DatePicker']
    VortDialog: typeof import('@/components/vort/dialog')['Dialog']
    VortDivider: typeof import('@/components/vort/divider')['Divider']
    VortDrawer: typeof import('@/components/vort/drawer')['Drawer']
    VortDropdown: typeof import('@/components/vort/dropdown')['Dropdown']
    VortDropdownMenuItem: typeof import('@/components/vort/dropdown')['DropdownMenuItem']
    VortDropdownMenuSeparator: typeof import('@/components/vort/dropdown')['DropdownMenuSeparator']
    VortEditor: typeof import('@/components/vort-biz/editor')['VortEditor']
    VortForm: typeof import('@/components/vort/form')['Form']
    VortFormItem: typeof import('@/components/vort/form')['FormItem']
    VortInput: typeof import('@/components/vort/input')['Input']
    VortInputNumber: typeof import('@/components/vort/input')['InputNumber']
    VortInputPassword: typeof import('@/components/vort/input')['InputPassword']
    VortInputSearch: typeof import('@/components/vort/input')['InputSearch']
    VortPagination: typeof import('@/components/vort/pagination')['Pagination']
    VortPopconfirm: typeof import('@/components/vort/popconfirm')['Popconfirm']
    VortRadioButton: typeof import('@/components/vort/radio')['RadioButton']
    VortRadioGroup: typeof import('@/components/vort/radio')['RadioGroup']
    VortRangePicker: typeof import('@/components/vort/date-picker')['RangePicker']
    VortScrollbar: typeof import('@/components/vort/scrollbar')['Scrollbar']
    VortSelect: typeof import('@/components/vort/select')['Select']
    VortSelectOption: typeof import('@/components/vort/select')['SelectOption']
    VortSpin: typeof import('@/components/vort/spin')['Spin']
    VortSwitch: typeof import('@/components/vort/switch')['Switch']
    VortTable: typeof import('@/components/vort/table')['Table']
    VortTableColumn: typeof import('@/components/vort/table')['TableColumn']
    VortTabPane: typeof import('@/components/vort/tabs')['TabPane']
    VortTabs: typeof import('@/components/vort/tabs')['Tabs']
    VortTag: typeof import('@/components/vort/tag')['Tag']
    VortTextarea: typeof import('@/components/vort/textarea')['Textarea']
    VortTimeline: typeof import('@/components/vort/timeline')['Timeline']
    VortTimelineItem: typeof import('@/components/vort/timeline')['TimelineItem']
    VortTooltip: typeof import('@/components/vort/tooltip')['Tooltip']
  }
}
