/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAssistButton: typeof import('@/components/vort-biz/ai-assist-button')['AiAssistButton']
    DeleteRecord: typeof import('@/components/vort-biz/delete-record')['DeleteRecord']
    MarkdownView: typeof import('@/components/vort-biz/editor')['MarkdownView']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableActions: typeof import('@/components/vort-biz/table-actions')['TableActions']
    TableActionsItem: typeof import('@/components/vort-biz/table-actions')['TableActionsItem']
    TableActionsMoreItem: typeof import('@/components/vort-biz/table-actions')['TableActionsMoreItem']
    VortAlert: typeof import('@openvort/vort-ui')['Alert']
    VortAutoComplete: typeof import('@openvort/vort-ui')['AutoComplete']
    VortBadge: typeof import('@openvort/vort-ui')['Badge']
    VortButton: typeof import('@openvort/vort-ui')['Button']
    VortCard: typeof import('@openvort/vort-ui')['Card']
    VortCheckbox: typeof import('@openvort/vort-ui')['Checkbox']
    VortColorPicker: typeof import('@openvort/vort-ui')['ColorPicker']
    VortConfigProvider: typeof import('@openvort/vort-ui')['VortConfigProvider']
    VortDatePicker: typeof import('@openvort/vort-ui')['DatePicker']
    VortDialog: typeof import('@openvort/vort-ui')['Dialog']
    VortDivider: typeof import('@openvort/vort-ui')['Divider']
    VortDrawer: typeof import('@openvort/vort-ui')['Drawer']
    VortDropdown: typeof import('@openvort/vort-ui')['Dropdown']
    VortDropdownMenuItem: typeof import('@openvort/vort-ui')['DropdownMenuItem']
    VortDropdownMenuSeparator: typeof import('@openvort/vort-ui')['DropdownMenuSeparator']
    VortForm: typeof import('@openvort/vort-ui')['Form']
    VortFormItem: typeof import('@openvort/vort-ui')['FormItem']
    VortInput: typeof import('@openvort/vort-ui')['Input']
    VortInputNumber: typeof import('@openvort/vort-ui')['InputNumber']
    VortInputPassword: typeof import('@openvort/vort-ui')['InputPassword']
    VortInputSearch: typeof import('@openvort/vort-ui')['InputSearch']
    VortPagination: typeof import('@openvort/vort-ui')['Pagination']
    VortPopconfirm: typeof import('@openvort/vort-ui')['Popconfirm']
    VortPopover: typeof import('@openvort/vort-ui')['Popover']
    VortRadioButton: typeof import('@openvort/vort-ui')['RadioButton']
    VortRadioGroup: typeof import('@openvort/vort-ui')['RadioGroup']
    VortRangePicker: typeof import('@openvort/vort-ui')['RangePicker']
    VortScrollbar: typeof import('@openvort/vort-ui')['Scrollbar']
    VortSelect: typeof import('@openvort/vort-ui')['Select']
    VortSelectOption: typeof import('@openvort/vort-ui')['SelectOption']
    VortSpin: typeof import('@openvort/vort-ui')['Spin']
    VortStatistic: typeof import('@openvort/vort-ui')['Statistic']
    VortSteps: typeof import('@openvort/vort-ui')['Steps']
    VortSwitch: typeof import('@openvort/vort-ui')['Switch']
    VortTable: typeof import('@openvort/vort-ui')['Table']
    VortTableColumn: typeof import('@openvort/vort-ui')['TableColumn']
    VortTabPane: typeof import('@openvort/vort-ui')['TabPane']
    VortTabs: typeof import('@openvort/vort-ui')['Tabs']
    VortTag: typeof import('@openvort/vort-ui')['Tag']
    VortTextarea: typeof import('@openvort/vort-ui')['Textarea']
    VortTimeline: typeof import('@openvort/vort-ui')['Timeline']
    VortTimelineItem: typeof import('@openvort/vort-ui')['TimelineItem']
    VortTimePicker: typeof import('@openvort/vort-ui')['TimePicker']
    VortTooltip: typeof import('@openvort/vort-ui')['Tooltip']
    VortUploadDragger: typeof import('@openvort/vort-ui')['UploadDragger']
  }
}
