/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAssistButton: typeof import('@/components/vort-biz/ai-assist-button')['AiAssistButton']
    DeleteRecord: typeof import('@/components/vort-biz/delete-record')['DeleteRecord']
    MarkdownView: typeof import('@/components/vort-biz/editor')['MarkdownView']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VortAlert: typeof import('@openvort/vort-ui')['Alert']
    VortButton: typeof import('@openvort/vort-ui')['Button']
    VortCard: typeof import('@openvort/vort-ui')['Card']
    VortCheckbox: typeof import('@openvort/vort-ui')['Checkbox']
    VortDatePicker: typeof import('@openvort/vort-ui')['DatePicker']
    VortDialog: typeof import('@openvort/vort-ui')['Dialog']
    VortDivider: typeof import('@openvort/vort-ui')['Divider']
    VortDrawer: typeof import('@openvort/vort-ui')['Drawer']
    VortDropdown: typeof import('@openvort/vort-ui')['Dropdown']
    VortDropdownMenuItem: typeof import('@openvort/vort-ui')['DropdownMenuItem']
    VortDropdownMenuSeparator: typeof import('@openvort/vort-ui')['DropdownMenuSeparator']
    VortEditor: typeof import('@/components/vort-biz/editor')['VortEditor']
    VortForm: typeof import('@openvort/vort-ui')['Form']
    VortFormItem: typeof import('@openvort/vort-ui')['FormItem']
    VortInput: typeof import('@openvort/vort-ui')['Input']
    VortInputNumber: typeof import('@openvort/vort-ui')['InputNumber']
    VortInputPassword: typeof import('@openvort/vort-ui')['InputPassword']
    VortInputSearch: typeof import('@openvort/vort-ui')['InputSearch']
    VortOption: typeof import('@openvort/vort-ui')['Option']
    VortPagination: typeof import('@openvort/vort-ui')['Pagination']
    VortPopconfirm: typeof import('@openvort/vort-ui')['Popconfirm']
    VortRadioButton: typeof import('@openvort/vort-ui')['RadioButton']
    VortRadioGroup: typeof import('@openvort/vort-ui')['RadioGroup']
    VortScrollbar: typeof import('@openvort/vort-ui')['Scrollbar']
    VortSelect: typeof import('@openvort/vort-ui')['Select']
    VortSelectOption: typeof import('@openvort/vort-ui')['SelectOption']
    VortSpin: typeof import('@openvort/vort-ui')['Spin']
    VortSwitch: typeof import('@openvort/vort-ui')['Switch']
    VortTable: typeof import('@openvort/vort-ui')['Table']
    VortTableColumn: typeof import('@openvort/vort-ui')['TableColumn']
    VortTabPane: typeof import('@openvort/vort-ui')['TabPane']
    VortTabs: typeof import('@openvort/vort-ui')['Tabs']
    VortTag: typeof import('@openvort/vort-ui')['Tag']
    VortTextarea: typeof import('@openvort/vort-ui')['Textarea']
    VortTooltip: typeof import('@openvort/vort-ui')['Tooltip']
  }
}
